from time import sleep
import pyautogui
pyautogui.PAUSE = 0.5
pyautogui.confirm("A manutenção automática começará quando você ocnfirmar:")
pyautogui.hotkey("winleft", "r")
pyautogui.typewrite('cmd')
pyautogui.press('enter')
sleep(1)
pyautogui.hotkey("winleft", "up")
#pyautogui.click(x=1040, y=152, button='left')
pyautogui.typewrite('systeminfo')
pyautogui.press('enter')
sleep(5)
pyautogui.hotkey("winleft", "left")
pyautogui.typewrite('ping 8.8.8.8')
pyautogui.press('enter')
sleep(6)
pyautogui.typewrite('exit')
pyautogui.press('enter')
pyautogui.hotkey("winleft", "r")
pyautogui.typewrite('%windir%\system32\dfrgui.exe')
pyautogui.press('enter')
sleep(4)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('enter')
sleep(2)
pyautogui.alert("Desfragmentação sendo executada, aguarde a sua conclusão.")
